"""
Text export functionality for GPT-5.2 keyword categorization results.
"""

from typing import Dict, Any
from datetime import datetime


def format_results_as_text(results: Dict[str, Any]) -> str:
    """
    Format GPT-5.2 keyword categorization results as a readable text document.
    
    Args:
        results: Dictionary containing categorized keywords and SEO metadata
        
    Returns:
        Formatted text string
    """
    if "error" in results:
        return f"Error: {results['error']}"
    
    text_lines = []
    text_lines.append("=" * 70)
    text_lines.append("KEYWORD CATEGORIZATION RESULTS")
    text_lines.append("Generated by GPT-5.2")
    text_lines.append(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    text_lines.append("=" * 70)
    text_lines.append("")
    
    # SEO Metadata Section
    text_lines.append("SEO METADATA")
    text_lines.append("-" * 70)
    text_lines.append("")
    
    focus_keyphrase = results.get("FocusKeyphrase", "")
    if focus_keyphrase:
        text_lines.append(f"Focus Keyphrase: {focus_keyphrase}")
    else:
        text_lines.append("Focus Keyphrase: (not provided)")
    
    text_lines.append("")
    
    seo_title = results.get("SEOTitle", "")
    if seo_title:
        text_lines.append(f"SEO Title: {seo_title}")
    else:
        text_lines.append("SEO Title: (not provided)")
    
    text_lines.append("")
    
    seo_excerpt = results.get("SEOExcerpt", "")
    if seo_excerpt:
        text_lines.append(f"SEO Excerpt: {seo_excerpt}")
    else:
        text_lines.append("SEO Excerpt: (not provided)")
    
    text_lines.append("")
    text_lines.append("")
    
    # Keyword Categories Section
    text_lines.append("KEYWORD CATEGORIES")
    text_lines.append("-" * 70)
    text_lines.append("")
    
    categories = [
        ("HIGH SEARCH VOLUME KEYWORDS", results.get("HighSearchVolumeKeywords", [])),
        ("HIGH GROWTH KEYWORDS", results.get("HighGrowthKeywords", [])),
        ("LONG TAIL KEYWORDS", results.get("LongTailKeywords", [])),
        ("NICHE EMERGING KEYWORDS", results.get("NicheEmergingKeywords", [])),
        ("ACTION ORIENTED KEYWORDS", results.get("ActionOrientedKeywords", [])),
    ]
    
    for category_name, keywords in categories:
        text_lines.append(category_name)
        text_lines.append("-" * 70)
        
        if keywords and keywords != "No applicable keywords.":
            if isinstance(keywords, list):
                for i, keyword in enumerate(keywords, 1):
                    text_lines.append(f"  {i}. {keyword}")
            else:
                text_lines.append(f"  {keywords}")
        else:
            text_lines.append("  No applicable keywords.")
        
        text_lines.append("")
    
    text_lines.append("=" * 70)
    text_lines.append("End of Report")
    text_lines.append("=" * 70)
    
    return "\n".join(text_lines)

